### ISSUE TITLE
Collation customization: How is it exposed in text-icu?

### ISSUE THREAD

**Issue by njbart** [haskell/text-icu#35]
It appears that ICU provides mechanisms for customizing collation (described at http://userguide.icu-project.org/collation/customization).

I’d be grateful for a pointer as to if, and if so, how this is exposed in the haskell text-icu package.

**Comment by na4zagin3** [comment]
In order to customize collations, we need [ucol_openRules()](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/ucol_8h.html#a39ccd61fb814dc0d2e759bc0cfe4c80d) and [ucol_getRules()](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/ucol_8h.html#a47699dcfa9c862b4011aea1927c53d4b)/[ucol_getRulesEx()](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/ucol_8h.html#a0eed45e3aef17e79116a77bf9b692bc5) to be exposed.  If no one is going to add support of them, let me do that.
